"""es_ingreso_operativo_categoria

Revision ID: 41ad180f8623
Revises: 1a11310afd08
Create Date: 2026-05-02 05:57:49.713565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ad180f8623'
down_revision: Union[str, Sequence[str], None] = '1a11310afd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_caja', schema=None) as batch_op:
        # server_default=false() para que no falle con filas existentes
        batch_op.add_column(sa.Column(
            'es_ingreso_operativo', sa.Boolean(),
            nullable=False, server_default=sa.false(),
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_caja', schema=None) as batch_op:
        batch_op.drop_column('es_ingreso_operativo')

    # ### end Alembic commands ###
