"""id_cliente_relacionado_movimiento

Revision ID: 7042dc75279d
Revises: 41ad180f8623
Create Date: 2026-05-02 06:03:50.075743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7042dc75279d'
down_revision: Union[str, Sequence[str], None] = '41ad180f8623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cliente_relacionado', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimientos_caja_id_cliente_relacionado'), ['id_cliente_relacionado'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_id_cliente_relacionado'))
        batch_op.drop_column('id_cliente_relacionado')

    # ### end Alembic commands ###
