"""proveedores_y_facturas

Revision ID: 804731e3a11c
Revises: c6466afca03d
Create Date: 2026-05-02 09:03:09.334399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804731e3a11c'
down_revision: Union[str, Sequence[str], None] = 'c6466afca03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cuit', sa.String(), nullable=True),
    sa.Column('contacto', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_cuit'), ['cuit'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedores_nombre'), ['nombre'], unique=False)

    op.create_table('facturas_proveedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas_proveedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_proveedor_fecha_emision'), ['fecha_emision'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_proveedor_fecha_vencimiento'), ['fecha_vencimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_proveedor_id_proveedor'), ['id_proveedor'], unique=False)

    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_factura_proveedor', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimientos_caja_id_factura_proveedor'), ['id_factura_proveedor'], unique=False)
        batch_op.create_foreign_key('fk_movimientos_caja_id_factura_proveedor', 'facturas_proveedor', ['id_factura_proveedor'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimientos_caja_id_factura_proveedor', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_id_factura_proveedor'))
        batch_op.drop_column('id_factura_proveedor')

    with op.batch_alter_table('facturas_proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_proveedor_id_proveedor'))
        batch_op.drop_index(batch_op.f('ix_facturas_proveedor_fecha_vencimiento'))
        batch_op.drop_index(batch_op.f('ix_facturas_proveedor_fecha_emision'))

    op.drop_table('facturas_proveedor')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_nombre'))
        batch_op.drop_index(batch_op.f('ix_proveedores_cuit'))

    op.drop_table('proveedores')
    # ### end Alembic commands ###
