"""linea_num_detalle_ventas

Revision ID: 9a7d25737acc
Revises: 7042dc75279d
Create Date: 2026-05-02 07:46:24.779499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7d25737acc'
down_revision: Union[str, Sequence[str], None] = '7042dc75279d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'linea_num', sa.Integer(),
            nullable=False, server_default='0',
        ))

    # Backfill: asignar linea_num secuencial por id_venta para filas existentes.
    # Las filas se ordenan por id (orden de inserción), se asignan números
    # secuenciales 0, 1, 2, ... dentro de cada venta.
    conn = op.get_bind()

    # Obtener todas las filas ordenadas por venta e id
    rows = conn.execute(sa.text(
        "SELECT id, id_venta FROM detalle_ventas ORDER BY id_venta, id"
    )).fetchall()

    # Agrupar por venta y asignar linea_num
    updates = []
    venta_actual = None
    linea_num = 0

    for row_id, id_venta in rows:
        if id_venta != venta_actual:
            venta_actual = id_venta
            linea_num = 0
        updates.append({"id": row_id, "linea_num": linea_num})
        linea_num += 1

    # Aplicar updates en lotes
    for update in updates:
        conn.execute(
            sa.text("UPDATE detalle_ventas SET linea_num = :linea_num WHERE id = :id"),
            {"linea_num": update["linea_num"], "id": update["id"]},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_column('linea_num')

    # ### end Alembic commands ###
