"""cierre_caja

Revision ID: c6466afca03d
Revises: 9a7d25737acc
Create Date: 2026-05-02 08:51:30.880574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6466afca03d'
down_revision: Union[str, Sequence[str], None] = '9a7d25737acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierres_caja',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('caja', sa.String(), nullable=False),
    sa.Column('saldo_cierre', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caja'], ['cajas.nombre_normalizado'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'caja', name='uq_cierre_fecha_caja')
    )
    with op.batch_alter_table('cierres_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cierres_caja_caja'), ['caja'], unique=False)
        batch_op.create_index(batch_op.f('ix_cierres_caja_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cierres_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cierres_caja_fecha'))
        batch_op.drop_index(batch_op.f('ix_cierres_caja_caja'))

    op.drop_table('cierres_caja')
    # ### end Alembic commands ###
